describe('Formulario de registro', () => {
  it('Validar el llenado del formulario de registro', () => {
    cy.visit('https://opencart.abstracta.us/')
    cy.get('.dropdown > .dropdown-toggle > .hidden-xs').click({ force: true })
    cy.get('.dropdown-menu > :nth-child(1) > a').click({ force: true })
    cy.get('#input-firstname').type('Juan Manuel')
    cy.get('#input-lastname').type('Lopez Rodriguez')
    cy.get('#input-email').type('froufanalloidoi-2711@yopmail.com')
    cy.get('#input-telephone').type('3366998855')
    cy.get('#input-password').type('Test12345.')
    cy.get('#input-confirm').type('Test12345.')
    cy.get('[type="checkbox"]').click({ force: true })
    cy.get('.pull-right > .btn').click({ force: true })
    cy.get('.alert').should('be.visible')
    cy.get('.alert').should('include.text', 'Warning: E-Mail Address is already registered!')
  })
})


describe('Inicio de sesión', () => {
  it('Validar el correcto inicio de sesión', () => {
    cy.visit('https://opencart.abstracta.us/')
    cy.get('.dropdown > .dropdown-toggle > .hidden-xs').click({ force: true })
    cy.get('.dropdown-menu > :nth-child(2) > a').click({ force: true })
    cy.get('#input-email').type('froufanalloidoi-2711@yopmail.com')
    cy.get('#input-password').type('Test12345.')
    cy.get('form > .btn').click({ force: true })
    cy.get('#content > :nth-child(1)').should('be.visible')
    cy.get('#content > :nth-child(1)').should('have.text', 'My Account')
    cy.get('#content > :nth-child(2) > :nth-child(1) > a').should('be.visible')
    cy.get('#content > :nth-child(2) > :nth-child(1) > a').should('have.text', 'Edit Account')
    cy.get('#content > :nth-child(3)').should('be.visible')
    cy.get('#content > :nth-child(3)').should('have.text', 'My Orders')
    cy.get('#content > :nth-child(4) > :nth-child(1) > a').should('be.visible')
    cy.get('#content > :nth-child(4) > :nth-child(1) > a').should('have.text', 'Order History')
    cy.get('#content > :nth-child(4) > :nth-child(3) > a').should('be.visible')
    cy.get('#content > :nth-child(4) > :nth-child(3) > a').should('have.text', 'Reward Points')
    cy.get(':nth-child(4) > :nth-child(5) > a').should('be.visible')
    cy.get(':nth-child(4) > :nth-child(5) > a').should('have.text', 'Transactions')
    })
})

describe('Reestablecimiento de contraseña', () => {
  it('Validar el correcto reestablecimiento de contraseña', () => {
    cy.visit('https://opencart.abstracta.us/')
    cy.get('.dropdown > .dropdown-toggle > .hidden-xs').click({ force: true })
    cy.get('.dropdown-menu > :nth-child(2) > a').click({ force: true })
    cy.get('form > :nth-child(2) > a').click({ force: true })
    cy.get('#input-email').type('froufanalloidoi-2711@yopmail.com')
    cy.get('.pull-right > .btn').click({ force: true })
    cy.get('.alert').should('be.visible')
    cy.get('.alert').should('include.text', 'An email with a confirmation link has been sent your email address.')
    })
})

describe('Proceso de compra', () => {
  it('Validar el correcto proceso de compra completo', () => {
    cy.visit('https://opencart.abstracta.us/')

    cy.get('.dropdown > .dropdown-toggle > .hidden-xs').click({ force: true })
    cy.get('.dropdown-menu > :nth-child(2) > a').click({ force: true })
    cy.get('#input-email').type('froufanalloidoi-2711@yopmail.com', { delay: 100 })
    cy.get('#input-password').type('Test12345.', { delay: 100 })
    cy.get('form > .btn').click({ force: true })
    cy.wait(1000)
    cy.get('.nav > :nth-child(2) > .dropdown-toggle').click({ force: true })
    cy.get('.open > .dropdown-menu > .see-all').should('be.visible')
    cy.wait(1000)
    cy.get('.open > .dropdown-menu > .see-all').click
    cy.visit('https://opencart.abstracta.us/index.php?route=product/category&path=18')
    cy.get(':nth-child(4) > .product-thumb > :nth-child(2) > .caption > h4 > a').scrollIntoView().should('be.visible')
    cy.wait(1000)
    cy.get('#content > div:nth-child(7) > div:nth-child(4) > div > div:nth-child(2) > div.button-group > button:nth-child(1)').click({ force: true })
    cy.get('.alert').should('be.visible')
    cy.get('.alert').should('include.text', 'Success: You have added MacBook Pro to your shopping cart!')
    cy.get('#search > .form-control').type('Samsung Galaxy', { delay: 100 })
    cy.wait(1000)
    cy.get('.input-group-btn > .btn').click({ force: true })
    cy.wait(1000)
    cy.get('#content > div:nth-child(8) > div > div > div:nth-child(2) > div.button-group > button:nth-child(1) > span').click({ force: true })
    cy.get('.alert').should('be.visible')
    cy.get('.alert').should('include.text', 'Success: You have added Samsung Galaxy Tab 10.1 to your shopping cart!')
    cy.wait(1000)
    cy.get('.btn-inverse').click({ force: true })
    cy.get(':nth-child(1) > :nth-child(5) > .btn').should('be.visible')
    cy.wait(1000)
    cy.get(':nth-child(1) > :nth-child(5) > .btn').click({ force: true })
    cy.wait(1000)
    cy.get('#content > div:nth-child(8) > div > div > div:nth-child(2) > div.button-group > button:nth-child(1) > span').click({ force: true })
    cy.get('.alert').should('be.visible')
    cy.get('.alert').should('include.text', 'Success: You have added Samsung Galaxy Tab 10.1 to your shopping cart!')
    cy.wait(1000)
    cy.get('.btn-inverse').click({ force: true })
    cy.get('[href="https://opencart.abstracta.us:443/index.php?route=checkout/checkout"] > strong').should('be.visible')
    cy.wait(1000)
    cy.get('[href="https://opencart.abstracta.us:443/index.php?route=checkout/checkout"] > strong').click({ force: true })
    cy.wait(1000)

    cy.get('#button-payment-address').click({ force: true })
    cy.wait(1000)
    cy.get('#button-shipping-address').click({ force: true })
    cy.wait(1000)
    cy.get('#button-shipping-method').click({ force: true })
    cy.wait(1000)
    cy.get('#collapse-payment-method > .panel-body > :nth-child(3) > label > input').click({ force: true })
    cy.wait(1000)
    cy.get('[type="checkbox"]').click({ force: true })
    cy.wait(1000)
    cy.get('#button-payment-method').click({ force: true })
    cy.wait(1000)
    cy.get('#button-confirm').click
    cy.visit('https://opencart.abstracta.us/index.php?route=checkout/success')

    cy.get('#content > h1').should('include.text', 'Your order has been placed!')

    })
})
